# Generated by Django 5.1 on 2024-08-27 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_tag", models.CharField(max_length=200)),
                ("event_name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                (
                    "time",
                    models.TimeField(
                        blank=True, default=datetime.time(0, 0), null=True
                    ),
                ),
                ("image_url", models.URLField()),
                ("city", models.CharField(max_length=50)),
                ("location", models.TextField()),
                ("description", models.TextField(default="no description")),
                (
                    "booking_url",
                    models.URLField(
                        default="https://insider.in/event/u1s-long-drive-live-in-concert-coimbatore-oct12-2024/buy-page/shows/65cda8bb66eb4b000aaf16e9"
                    ),
                ),
            ],
        ),
    ]
